name: Feature Request
description: Suggest a new feature or enhancement for php-cuid2
title: '[Feature]: '
labels: ['Status: Review Needed', 'Priority: Low']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also thought about...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the library would this feature affect?
      multiple: true
      options:
        - CUID2 Generation
        - Validation
        - Counter
        - Fingerprint
        - Base Conversion
        - Configuration Options
        - Performance Optimization
        - New Feature (not yet supported)
        - Other
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Show how you'd like to use this feature
      render: php
      placeholder: |
        <?php
        use Visus\Cuid2\Cuid2;

        $cuid2 = new Cuid2();
        // Your proposed API usage here
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important for my use case
        - Critical blocker
    validations:
      required: true

  - type: textarea
    id: cuid2-spec
    attributes:
      label: CUID2 Specification Support
      description: Is this feature part of the official CUID2 specification? If so, please provide a link
      placeholder: https://github.com/paralleldrive/cuid2#...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Any additional information that might be helpful
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested already
          required: true
        - label: This feature aligns with the CUID2 specification and library goals
          required: false
        - label: I am willing to contribute this feature via a pull request
          required: false
