name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "renovate.json"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/release.yml"

  pull_request:
    paths-ignore:
      - "**.md"
      - "renovate.json"
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/workflows/release.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          show-progress: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 'latest'
          tools: composer
          coverage: none

      - name: Composer Install
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          custom-cache-key: composer-${{ runner.os }}-${{ hashFiles('**/composer.json') }}

      - name: Check Syntax
        run: composer dev:lint:syntax

      - name: Check Code Style
        run: composer dev:lint:style

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          show-progress: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 'latest'
          tools: composer
          coverage: none

      - name: Composer Install
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          custom-cache-key: composer-${{ runner.os }}-${{ hashFiles('**/composer.json') }}

      - name: Run Static Analysis
        run: composer dev:analyze:phpstan

  code-coverage:
    name: Code Coverage
    needs: [coding-standards, static-analysis]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          show-progress: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: 'latest'
          tools: composer
          extensions: gmp
          coverage: xdebug

      - name: Composer Install
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          custom-cache-key: composer-${{ runner.os }}-${{ hashFiles('**/composer.json') }}

      - name: Run Tests with Coverage
        run: composer dev:test:coverage:ci

      - name: Upload to SonarCloud
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  unit-tests:
    name: Unit Tests
    needs: [coding-standards, static-analysis]
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
            php-version: ['8.3', '8.4', '8.5']
            os: [ubuntu-latest, windows-latest]

    steps:
      - name: Configure Git for Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          git config --system core.autocrlf false
          git config --system core.eol lf

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          show-progress: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          extensions: gmp
          coverage: none

      - name: Composer Install
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # 4.0.0
        with:
          custom-cache-key: composer-${{ matrix.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}

      - name: Run Unit Tests
        run: composer dev:test:unit
