name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - '**/renovate.json'
  pull_request:
    paths-ignore:
      - "**.md"
      - '**/renovate.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-composer-            
      - name: Composer
        run: |
          composer update --no-interaction --no-progress --no-suggest --prefer-dist
          composer normalize --dry-run
          composer validate
      - name: PHPStan
        run: composer phpstan -- --ansi --xdebug
      - name: Psalm
        run: composer psalm -- --shepherd

  unit-tests:
    name: Unit Tests
    needs: [static-analysis]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            restore-keys: |
              ${{ runner.os }}-composer-            
      - name: Composer
        run: |
          composer update --no-interaction --no-progress --no-suggest --prefer-dist
          composer normalize --dry-run
          composer validate
      - name: PHPUnit
        run: vendor/bin/phpunit --coverage-text --coverage-clover build/logs/coverage.xml || true
      - name: Codacy Coverage
        if: always()
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: build/logs/coverage.xml
